#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/hesabdesk/hesabdesk /usr/bin/hesabdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/hesabdesk.service ]; then
			rm /etc/systemd/system/hesabdesk.service /usr/lib/systemd/system/hesabdesk.service /usr/lib/systemd/user/hesabdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/hesabdesk/files/systemd/hesabdesk.service /usr/lib/systemd/system/hesabdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload hesabdesk.service: Unit hesabdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/hesabdesk.service:10: Executable path is not absolute: pkill -f "hesabdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/hesabdesk.service
		fi
		systemctl daemon-reload
		systemctl enable hesabdesk
		systemctl start hesabdesk
	fi
fi
